Immersion freezing update
compdyn/partmc pull request #205
Opened 2024-11-27 05:58 UTC by tangwhiap

Add the immersion freezing simulation codes, freezing test case, and freezing scenario.

2024-11-29 18:44 UTC, jcurtis2 reviewed
@tangwhiap I've done a quick first pass of a review of this PR. Let me know if anything is unclear.

2024-11-29 18:44 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +        allocate(H2O_frac(aero_state_n_part(aero_state)))
```suggestion
```

2024-11-30 03:35 UTC, tangwhiap commented on scenarios/7_freezing/0_README.md
Hi Jeff, if the do_immersion_freezing is set to yes, the immersion_freezing scheme will denote which scheme would be used. In this 7_freezing scenario, all the experiments are using ABIFM, I will emphasize his in README file.

2024-11-30 03:43 UTC, tangwhiap commented on src/aero_particle.F90
> +!>>>>>>> 2341ef410d6f49f3169b8461b5fa8c89dbd3c7a2
Yes, the units are correct.

2024-12-03 18:02 UTC, tangwhiap commented on src/ice_nucleation.F90
> +        deallocate(H2O_frac)
Keep it temporarily (fix it in the future)

2024-12-11 14:50 UTC, tangwhiap commented on scenarios/7_freezing/standard_setting/run_part.spec
> +rand_init 1                     # random initialization (0 to auto-generate)
No, just because the results in my paper are generated by setting rand_init=1, it is a way to precisely reproduce those results.

2024-12-11 15:27 UTC, tangwhiap commented on src/aero_state.F90
> +            "aero_ice_shape_phi", must_be_present=.false.)
Those variables only present when the do_condense=True and do_immersion_freezing=True

2024-12-11 17:39 UTC, tangwhiap commented on src/ice_nucleation.F90
> +                        endif
If there any rule of the code (such as 408545686, 353290871 ...) selection for a typical warning message?

2025-01-14 01:31 UTC, jcurtis2 requested changes

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    allocate(total_masses(aero_state_n_part(aero_state)))
Maybe add a comment that we do this to avoid a compiler issue.

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    allocate(H2O_frac(aero_state_n_part(aero_state)))
These don't seem to cause an error when removed. However maybe they could be kept to look similar to the others.

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    integer :: n_entry, ind, spec_bin = 13
None of these are used.

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    real(kind=dp) :: aerosol_dry_radius, aerosol_radius, rand
First two appear unused?

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    real(kind=dp) :: pvs, pis
Unused

```suggestion
```

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    integer :: clock_start, clock_end
Unused.

```suggestion
```

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    real(kind=dp) :: p_freeze, p_frozen
```suggestion
    real(kind=dp) :: p_freeze

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    real(kind=dp) :: tmp
Unused.

```suggestion
```

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    real(kind=dp) :: abifm_m, abifm_c
Appear unused

```suggestion
```

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    logical :: freeze_thisTime
Unused.

```suggestion
```

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    real(kind=dp) :: p_freeze, p_frozen
```suggestion
    real(kind=dp) :: p_freeze
```

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    integer :: i_part, i_bin, i_class, n_bins, n_class
Some of these are unused.

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    !> Immersion freezing scheme type (e.g., 1:constant rate, 2:sigular, 3:ABIFM).
Consider removing the e.g. portion as its specific to the parameters and not this subroutine. They could in theory change.

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +  subroutine immersion_freezing(aero_state, aero_data, env_state_initial, &
This subroutine should be named something with the file name in it like we do for other processes (such as `ice_nucleation_immersion_freezing`.

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
In general, subroutines and function naming convention has the file name before it and this applies even for things that aren't operating on a type (see mosaic.F90, condense.F90, etc.)

See comment on `immersion_freezing` for an example.

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    loop_count = 0
Appears unused?

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +             loop_count = loop_count + 1
Appears unused?

```suggestion
```

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +
Appears not needed.

```suggestion
```

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +  subroutine immersion_freezing_singular(aero_state, aero_data, env_state_initial, env_state_final)
`env_state_initial` is passed here and never used (and if this is correct, `env_state_final` can just become `env_state`).

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +       env_state_final, del_t, immersion_freezing_scheme_type, freezing_rate)
`env_state_initial` is passed here and never used (and if this is correct, `env_state_final` can just become `env_state`).

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    freezing_rate)
`env_state_initial` is passed here and never used (and if this is correct, `env_state_final` can just become `env_state`).

2025-01-14 01:31 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +  !> This subroutine applys the naive algorithm for reference.
```suggestion
  !> This subroutine applies the naive algorithm that checks each particle.
```

2025-01-22 20:11 UTC, tangwhiap commented on src/aero_state.F90
> +         sum(particle_num_concs)
I used the pack before but it will assert warning in compiling. (since aero_state%apa%particle(i_part)%frozen is a logical variable but particle_frozen(i_part) is integer.

2025-01-23 14:22 UTC, tangwhiap commented on test/freezing/test_freezing_theoretical.F90
I don't know what you mean by doxygen commenting. Can you tell me which line the problem is on?

2025-01-23 14:24 UTC, tangwhiap commented on src/ice_nucleation.F90
Let's discuss it later.

2025-01-28 20:46 UTC, tangwhiap commented on src/aero_particle.F90
> +    !!! Not true, need further discussion
Assumption is: If two particles coagulate, the overall freezing temperature is determined by the particle with higher freezing temperature.

2025-01-29 18:28 UTC, nriemer commented on src/aero_particle.F90
> +    !!! Not true, need further discussion
Wenhan and I met yesterday, and this is what we came up with to explain the underlying assumption.

2025-01-29 18:31 UTC, nriemer commented on test/freezing/test_freezing_theoretical.F90
@jcurtis2, we don't understand that comment, could you please clarify?

2025-01-29 18:36 UTC, nriemer commented on src/ice_nucleation.F90
Discussed it with Matt, and we converged on not moving the subroutines to aero_data.F90 
The reason is that these functions are very specific to IN, i.e., not generic enough. 

Regarding the second part of the comment: That is  a good point. We should not pass i_part and aero_state as argument. Instead, pass an individual particle. 

The rationale for this is to not pass more data than the subroutine needs since this makes it hard to read.

2025-02-01 00:13 UTC, jcurtis2 commented on test/freezing/test_freezing_theoretical.F90
Sure - the use of `!>` before a variable is for Doxygen to produce documentation and it is used for inputs and outputs of subroutines and functions. So this isn't needed here.

2025-02-01 00:18 UTC, jcurtis2 commented on src/aero_particle.F90
> +    !!! Not true, need further discussion
Sounds reasonable. Maybe change this further discussion comment to say this is the assumption.

I assume this can eventually depend somewhat on size as in a large, lower freezing temperature coagulating with a small but higher freezing temperature might exhibit different behavior than the other way around.

2025-02-02 03:14 UTC, tangwhiap commented on test/freezing/test_freezing_theoretical.F90
Do you mean just use "!" instead of "!>" ?

2025-02-19 21:32 UTC, jcurtis2 requested changes

2025-02-19 21:32 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +
```suggestion
```

2025-02-19 21:32 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    end do
Not sure why there is a loop here - isn't this just dry volume?

2025-02-19 21:32 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +       b_INAS = 8.934
Move outside the loop.

2025-02-19 21:32 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    real(kind=dp) :: freezing_rate
This is an argument. Move up and define.

2025-02-19 21:32 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    real(kind=dp) :: freezing_rate
These are arguments. move up and define.

2025-02-19 21:32 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    !do_coating, coating_spec, coating_ratio)
```suggestion

```

2025-02-19 21:57 UTC, tangwhiap commented on src/ice_nucleation.F90
> +    end do
Yes, just calculate the dry volume by looping all species.

2025-02-19 22:01 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    end do
We can change this to just use `aero_particle_dry_volume()`

2025-08-29 01:40 UTC, jcurtis2 requested changes
Just a few more things I've noted while taking a pass through for PyPartMC.

2025-08-29 01:40 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +  !> tempearture)
```suggestion
  !> Simulates melting: if the environmental temperature is above the freezing
  !> temperature of water, all particles are set to be unfrozen.
```

2025-08-29 01:40 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    b_INAS = 8.934
Where are these numbers from? Are these parameters? If so, maybe to make it more clear, they could be parameters up above in their variable declaration. Example: `real(kind=dp), parameter :: a_INAS = -0.517d0`

2025-08-29 01:40 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +  subroutine ABIFM_max_spec(aero_data, a_w_ice, i_spec_max, j_het_max)
Is there a reason that we have to know what species it is? it appears we only do something with the maximum rate.

I'd shorten the description a bit to what its purpose is which is finding the maximum heterogeneous ice nucleation rate coefficient.

2025-08-29 01:40 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +  !> generate it.
This description is leftover copy/paste from somewhere else.

```suggestion
  !> Read the specification for immersion freezing scheme.
```

2025-08-29 01:40 UTC, jcurtis2 commented on src/env_state.F90
> +  real(kind=dp) function env_state_saturated_vapor_pressure_water_2(T)
I can't seem to find where this is used. it is also a near duplicate to env_state_sat_vapor_pressure (just takes a different argument)

2025-08-29 01:40 UTC, jcurtis2 commented on src/env_state.F90
> +  real(kind=dp) function env_state_saturated_vapor_pressure_water(T)
Consider `wrt` (with respect to) added to this function and the ice one. If so, you'd have to check where it is called and make changes as well.

```suggestion
  real(kind=dp) function env_state_saturated_vapor_pressure_wrt_water(T)
```

2025-08-29 01:40 UTC, jcurtis2 commented on src/env_state.F90
> +  real(kind=dp) function env_state_saturated_vapor_pressure_water(T)
I also wonder why env_state isn't passed to this function given it is an env_state function?

2025-08-29 01:40 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    integer, intent(in) :: immersion_freezing_scheme_type
This should be moved up with the rest of the input/output arguments.

2025-08-29 16:06 UTC, slayoo commented on src/run_part.F90
> +       call ice_nucleation_singular_initialize(aero_state, aero_data)
this is now not yet called if using `timestep` or `timeblock` variants -> should be moved to the timestep logic

2025-09-12 21:18 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    !!   - \ref spec_file_format --- the input file text format
The description needs to be fixed to reflect how to run the different versions of freezing.

2025-09-15 00:10 UTC, tangwhiap commented on src/ice_nucleation.F90
> +  subroutine ABIFM_max_spec(aero_data, a_w_ice, i_spec_max, j_het_max)
Solved!

2025-09-15 00:16 UTC, jcurtis2 commented on src/run_part.F90
> +               "Error type of immersion freezing scheme")
This code appears to be unreachable. Model already errors out if an invalid scheme is specified.

```suggestion
```

And as a result of it being unreachable, the IMMERSION_FREEZING_SCHEME_ABIFM branch above it can also be removed since it does no additional spec file reading.

2025-09-15 00:24 UTC, tangwhiap commented on src/env_state.F90
> +  real(kind=dp) function env_state_saturated_vapor_pressure_water_2(T)
I have removed it.

2025-09-15 00:30 UTC, tangwhiap commented on src/env_state.F90
> +  real(kind=dp) function env_state_saturated_vapor_pressure_water(T)
Because this function only requires the temperature, `T` is the only necessary input. I thought you had previously suggested that I use `T` instead of `env_state` as the input—should I change it back to `env_state`?

2025-09-15 01:04 UTC, tangwhiap commented on src/env_state.F90
> +  real(kind=dp) function env_state_saturated_vapor_pressure_water(T)
Solved!

2025-09-15 01:04 UTC, tangwhiap commented on src/ice_nucleation.F90
> +    integer, intent(in) :: immersion_freezing_scheme_type
Solved!

2025-09-15 01:04 UTC, tangwhiap commented on src/ice_nucleation.F90
> +    !!   - \ref spec_file_format --- the input file text format
Solved!

2025-09-15 01:04 UTC, tangwhiap commented on src/run_part.F90
> +               "Error type of immersion freezing scheme")
Solved!

2025-09-15 01:11 UTC, tangwhiap commented on src/ice_nucleation.F90
> +    b_INAS = 8.934
I have moved these parameters to the spec file.

2025-09-15 01:23 UTC, jcurtis2 commented on src/env_state.F90
> +  real(kind=dp) function env_state_saturated_vapor_pressure_water(T)
Yes, you are right - I see where I suggested that. This was probably the simplest suggestion at the time as you had two functions that did the same thing (which isn't a great idea), one taking temperature and the other taking env_state.

I think that made this pretty confusing and in hindsight, we probably should apply a different fix. Not 100% sure what it should be at the moment.

The fact is, that all env_state functions take env_state as an input so this function is an outlier. So I think we need it to take env_state. However we also shouldn't have two functions that do exactly the same thing.

Two paths that I can think of:
 - Make an `env_state` in the theoretical_freezing.F90 code and then call those functions by passing an `env_state` that has it the temperature set. Then switch to have env_state as the input rather than temperature.
- A function that takes env_state that is just a wrapper to call another function that just takes temperature (and this function name shouldn't start with env_state). However, I don't know that we have any cases in the code that does something quite like that. And I'm not quite sure what file this function would actually exist in (it doesn't quite feel like it belongs in util.F90).

2025-09-15 13:09 UTC, tangwhiap commented on src/env_state.F90
> +  real(kind=dp) function env_state_saturated_vapor_pressure_water(T)
Thanks for your reply! I prefer the second approach since it wouldn’t complicate theoretical_freezing.F90. However, it would still be somewhat of an outlier. We can discuss this further.

2025-09-15 15:36 UTC, slayoo commented
closing and reopening to trigger codecov analysis in further commits

2025-09-25 01:21 UTC, slayoo commented on CMakeLists.txt
> +#>>>>>>> 2341ef410d6f49f3169b8461b5fa8c89dbd3c7a2
this seems to be a merge-conflict leftover to be removed?

2025-09-25 01:21 UTC, slayoo commented on doc/freezing/freezing.tex
would it be better to make it a part of the web-publishable doxygen html?

2025-09-25 01:21 UTC, slayoo commented on scenarios/6_camp/monarch_mod37/custom_species.json
IIUC, the lack of these additions was not detected by CI, it would be great to add a mechanism at least parsing all the scenario input on CI

2025-09-25 01:40 UTC, jcurtis2 commented on scenarios/6_camp/monarch_mod37/custom_species.json
Yeah, this is a fairly common occurrence. The urban_plume scenarios are often fixed but the scenarios that often require more libraries (SUNDIALs for condense, CAMP) are often overlooked. This is often as simple as missing a  spec file line change/addition. In this case, it would be a lack of adding things in aero_data.dat for most scenarios or a more special case in terms of the CAMP scenario. The CAMP test caught this, it was fixed in the test but not in the scenario til later.

I think that something that simply attempts to run a 0 second simulation will work in terms of reading in all inputs.

2026-01-20 20:20 UTC, jcurtis2 requested changes

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    total_vol = 0d0
```suggestion
```

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +       j_het = 10 ** (abifm_m  * (1 - a_w_ice) + abifm_c) * 10000
```suggestion
       j_het = 10d0 ** (abifm_m  * (1d0 - a_w_ice) + abifm_c) * 10000
```

Also define what the 10000 is.

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +  !> for each particles.
```suggestion
  !> Initialization for the singular scheme, sampling the freezing
  !> temperature for each particle.
```

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    implicit none
```suggestion

```

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +  end subroutine ice_nucleation_immersion_freezing_time_dependent
Fix all `enddo` and `endif` to be `end do` and `end if`

2026-01-20 20:20 UTC, jcurtis2 commented on test/freezing/test_freezing_theoretical.F90
> +    endif
```suggestion
    end if
```

2026-01-20 20:20 UTC, jcurtis2 commented on test/freezing/test_freezing_theoretical.F90
> +    elseif (immersion_freezing_scheme_type == &
```suggestion
    else if (immersion_freezing_scheme_type == &
```

2026-01-20 20:20 UTC, jcurtis2 commented on test/freezing/test_freezing_theoretical.F90
> +    endif
```suggestion
    if (trim(imf_scheme) == 'const') then
       immersion_freezing_scheme_type = IMMERSION_FREEZING_SCHEME_CONST
    else if (trim(imf_scheme) == 'singular') then
       immersion_freezing_scheme_type = IMMERSION_FREEZING_SCHEME_SINGULAR
    else if (trim(imf_scheme) == 'ABIFM') then
       immersion_freezing_scheme_type = IMMERSION_FREEZING_SCHEME_ABIFM
    else
       print*, "Unknown immersion freezing scheme: " // trim(imf_scheme)
       immersion_freezing_scheme_type = -1
    end if
```

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    endif
```suggestion
       end if
    end if
```

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    real(kind=dp), intent(in) :: INAS_a, INAS_b
Add comments and separate line per variable

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +       temp = (log(1 - p) + exp(-S * exp(-INAS_a * T0 + INAS_b))) / (-S)
```suggestion
       temp = (log(1d0 - p) + exp(-S * exp(-INAS_a * T0 + INAS_b))) / (-S)
```

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    end do
```suggestion
    end do
    
```

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +       env_state)
```suggestion
  subroutine ice_nucleation_immersion_freezing_singular(aero_state, &
       aero_data, env_state)
```

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +
```suggestion
```

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +                   del_t)
```suggestion
             p_freeze_max = ABIFM_Pfrz_max(diameter_max, aero_data, &
                   j_het_max, del_t)
```

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +             p_freeze_max = 1 - exp(freezing_rate * del_t)
```suggestion
             p_freeze_max = 1d0 - exp(freezing_rate * del_t)
```

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +
```suggestion
```

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +       end if
`p_freeze` for `IMMERSION_FREEZING_SCHEME_CONST` doesn't rely on the particle at all. I think it would be worth considering moving outside the loop.

2026-01-20 20:20 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +          endif
If I understand correctly, consider refactoring `p_freeze_max` outside all these loops for the constant case.

2026-01-20 20:20 UTC, jcurtis2 commented on src/aero_state.F90
> +         / sum(particle_num_concs)
It appears that I incorrectly suggested pack here and that we should avoid it when we aren't doing anything extra with the subset of particles. Sum with a mask is much more clear and efficient.

```suggestion
    aero_state_frozen_fraction = sum(particle_num_concs, mask=particle_frozen) &
         / sum(particle_num_concs)
```

2026-02-27 13:59 UTC, slayoo commented on src/ice_nucleation.F90
> +    implicit none
@jcurtis2, are you suggesting to remove it because there is `-fimplicit-none` in the Dockerfile? (it doesn't seem to be enforced by CMake)

2026-02-27 14:05 UTC, slayoo commented on doc/freezing/freezing.tex
leaving for a separate PR

2026-02-27 14:51 UTC, slayoo commented
@tangwhiap, codecov reports here that the following three cases are never tested:
-  `if (env_state%temp > const%water_freeze_temp)` never occurs in `ice_nucleation_melting`
- `if (aero_particle_new%frozen)` never occurs in `aero_particle_coagulate`
- `if (immersion_freezing_scheme_type == IMMERSION_FREEZING_SCHEME_ABIFM)` in `ice_nucleation_immersion_freezing_time_dependent_naive`

Also, there are two instances where the following comment is placed:
```
! FIXME: Do this to avoid compiler warning/error, fix it in the future.
```

2026-02-27 16:47 UTC, slayoo commented on test/freezing/test_freezing_theoretical.F90
> +          frozen_fraction = 1 - exp(freezing_rate * time)
@tangwhiap, @jcurtis2, here I'd suggest to define the rate as a positive number, and introduce a minus sign into the exponent

2026-02-27 17:21 UTC, slayoo commented
melting covered!
<img width="742" height="335" alt="image" src="https://github.com/user-attachments/assets/042167dc-ce8b-4491-b777-d7f0a9588d39" />

2026-02-27 18:48 UTC, jcurtis2 commented on src/ice_nucleation.F90
> +    implicit none
This is suggested because we have an implicit none at the module level - this one here is harmless but it is redundant (and I think we have possibly already removed others from elsewhere in this PR)

2026-02-27 18:56 UTC, jcurtis2 commented on test/freezing/test_freezing_theoretical.F90
> +          frozen_fraction = 1 - exp(freezing_rate * time)
Agreed - I found this a bit confusing initially (as I didn't check carefully enough that the rate was specified as a negative) so I think we should change it that the user specifies a positive value. While this isn't quite the same, we have these in the file and they have a much more familiar form of an exponential with a minus sign.

`temp = (log(1d0 - p) + exp(-S * exp(-INAS_a * T0 + INAS_b))) / (-S)`

`ABIFM_Pfrz_particle = 1 - exp(-j_het_x_area * del_t)`

Related, I don't think we ever check on freezing rate to assure its specified correctly - either making sure it is positive (if we want it positive) or negative if we keep it negative.

2026-02-27 23:01 UTC, jcurtis2 commented
> * `if (immersion_freezing_scheme_type == IMMERSION_FREEZING_SCHEME_ABIFM)` in `ice_nucleation_immersion_freezing_time_dependent_naive`
> 

This appears to be a false-positive in codecov as I've added print statements that are printed when running `test_freezing_4.sh`. I tried a few things to try to reorganize the code so it might detect that it is indeed tested with line continuations and optimization reduction.

> Also, there are two instances where the following comment is placed:
> 
> ```
> ! FIXME: Do this to avoid compiler warning/error, fix it in the future.
> ```

I've changed this to a WORKAROUND so that we do not actually insinuate that we can fix this problem https://github.com/compdyn/partmc/pull/205/commits/48b0a8589bfdb1474377011c47b53d05daaff3be rather than a FIXME.

2026-03-13 14:46 UTC, slayoo commented on doc/freezing/freezing.tex
> +    P_{\text{frz,}j}(\Delta t) = 1 - \exp\left(J_{\text{het}} \cdot A_j \cdot \Delta t \right) \label{eq:1}
minus missing?

2026-03-13 23:05 UTC, tangwhiap commented on test/freezing/test_freezing_theoretical.F90
> +          frozen_fraction = 1 - exp(freezing_rate * time)
I just fixed it, now the `freezing_rate` has a positive sign.

2026-03-13 23:06 UTC, tangwhiap commented on doc/freezing/freezing.tex
> +    P_{\text{frz,}j}(\Delta t) = 1 - \exp\left(J_{\text{het}} \cdot A_j \cdot \Delta t \right) \label{eq:1}
I fixed it by adding a minus sign to Eq. (1).

2026-03-16 20:46 UTC, slayoo commented on src/env_state.F90
> +  real(kind=dp) function env_state_saturated_vapor_pressure_water(T)
@jcurtis2 shall we leave this issue for another PR or work on a refactor here?

2026-03-19 14:29 UTC, slayoo commented
closing & reopening to trigger rebuilt against current `master` branch

2026-03-25 07:10 UTC, slayoo commented
@jcurtis2, @nriemer, @mwest1066, let's merge (and release, and unveil PyPartMC 2.0)!

2026-03-30 17:14 UTC, jcurtis2 commented on src/run_part.F90
> +       call ice_nucleation_singular_initialize(aero_state, aero_data)
Resolved this by moving the initialization code into `ice_nucleation_immersion_freezing`, which now checks that freezing temperatures are properly set for each particle before calling `ice_nucleation_immersion_freezing_singular`.

This avoids the issue you highlighted — which would have required PyPartMC users to manually call a function or set particle temperatures. It also fixes a bug where newly added particles would never have their freezing value initialized added

2026-03-30 22:21 UTC, jcurtis2 approved these changes

2026-03-30 22:38 UTC, merged